---

source_url: "https://raw.githubusercontent.com/shidahuilang/shuyuan/shuyuan/book.json"
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58"
connect_via_warp: true
connect_treads: 32
connect_timeout: 10
verify_threads: 8
verify_timeout: 60
verify_books:
  - name: "æ–—ç½—å¤§é™†"
    author: "å”å®¶ä¸‰å°‘"
verify_api: "http://127.0.0.1:8080"
excludes: [ "ç¦", "æ¼«", "æˆäºº", "è…", "ç”œ", "ğŸ§", "éŸ³ä¹", "å¹¿æ’­", "FM", "è€½", "åŒäºº", "å¬", "è‰æ¦´", "å›¾ç‰‡", "ğŸ”" ]
excludes_insensitive_case: [ "r18", "bl" ]
